Data Analysis

In [3]:
import pandas as pd
import sklearn
import numpy as np
import matplotlib.pyplot as plt
import matplotlib

In [4]:
data = pd.read_csv('Train_data.csv')

In [5]:
data

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,class
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25187,0,tcp,exec,RSTO,0,0,0,0,0,0,...,7,0.03,0.06,0.00,0.00,0.00,0.00,1.00,1.00,anomaly
25188,0,tcp,ftp_data,SF,334,0,0,0,0,0,...,39,1.00,0.00,1.00,0.18,0.00,0.00,0.00,0.00,anomaly
25189,0,tcp,private,REJ,0,0,0,0,0,0,...,13,0.05,0.07,0.00,0.00,0.00,0.00,1.00,1.00,anomaly
25190,0,tcp,nnsp,S0,0,0,0,0,0,0,...,20,0.08,0.06,0.00,0.00,1.00,1.00,0.00,0.00,anomaly
25191,0,tcp,finger,S0,0,0,0,0,0,0,...,49,0.19,0.03,0.01,0.00,1.00,1.00,0.00,0.00,anomaly

In [6]:
data.describe()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
count,25192.000000,2.519200e+04,2.519200e+04,25192.000000,25192.000000,25192.00000,25192.000000,25192.000000,25192.000000,25192.000000,...,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000,25192.000000
mean,305.054104,2.433063e+04,3.491847e+03,0.000079,0.023738,0.00004,0.198039,0.001191,0.394768,0.227850,...,182.532074,115.063036,0.519791,0.082539,0.147453,0.031844,0.285800,0.279846,0.117800,0.118769
std,2686.555640,2.410805e+06,8.883072e+04,0.008910,0.260221,0.00630,2.154202,0.045418,0.488811,10.417352,...,98.993895,110.646850,0.448944,0.187191,0.308367,0.110575,0.445316,0.446075,0.305869,0.317333
min,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,84.000000,10.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,4.400000e+01,0.000000e+00,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,...,255.000000,61.000000,0.510000,0.030000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,2.790000e+02,5.302500e+02,0.000000,0.000000,0.00000,0.000000,0.000000,1.000000,0.000000,...,255.000000,255.000000,1.000000,0.070000,0.060000,0.020000,1.000000,1.000000,0.000000,0.000000
max,42862.000000,3.817091e+08,5.151385e+06,1.000000,3.000000,1.00000,77.000000,4.000000,1.000000,884.000000,...,255.000000,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [7]:
data.shape

(25192, 42)

In [8]:
data['class'].value_counts()

class
normal     13449
anomaly    11743
Name: count, dtype: int64

Data Processing

In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split

In [12]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

for column in data.columns:

    if data[column].dtype == 'object':

        data[column] = encoder.fit_transform(data[column])

In [13]:
X = data.drop(columns = ['duration','land','urgent','wrong_fragment','num_failed_logins','logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations','num_shells','num_access_files','num_outbound_cmds','is_host_login','is_guest_login','serror_rate','srv_serror_rate','rerror_rate','srv_rerror_rate','same_srv_rate','srv_diff_host_rate','dst_host_srv_diff_host_rate','dst_host_srv_serror_rate','dst_host_rerror_rate','dst_host_srv_rerror_rate','class'])
X.head()

,protocol_type,service,flag,src_bytes,dst_bytes,hot,count,srv_count,diff_srv_rate,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_serror_rate
0,1,19,9,491,0,0,2,2,0.00,150,25,0.17,0.03,0.17,0.00
1,2,41,9,146,0,0,13,1,0.15,255,1,0.00,0.60,0.88,0.00
2,1,46,5,0,0,0,123,6,0.07,255,26,0.10,0.05,0.00,1.00
3,1,22,9,232,8153,0,5,5,0.00,30,255,1.00,0.00,0.03,0.03
4,1,22,9,199,420,0,30,32,0.00,255,255,1.00,0.00,0.00,0.00

In [14]:
X.to_csv('X.csv', index=False)

In [15]:
features = X.columns
for feature in features:
    print(feature)

protocol_type
service
flag
src_bytes
dst_bytes
hot
count
srv_count
diff_srv_rate
dst_host_count
dst_host_srv_count
dst_host_same_srv_rate
dst_host_diff_srv_rate
dst_host_same_src_port_rate
dst_host_serror_rate

In [16]:
Y = data.drop(columns = ['duration','land','urgent','wrong_fragment','num_failed_logins','logged_in','num_compromised','root_shell','su_attempted','num_root','num_file_creations','num_shells','num_access_files','num_outbound_cmds','is_host_login','is_guest_login','serror_rate','srv_serror_rate','rerror_rate','srv_rerror_rate','same_srv_rate','srv_diff_host_rate','dst_host_srv_diff_host_rate','dst_host_srv_serror_rate','dst_host_rerror_rate','dst_host_srv_rerror_rate','protocol_type','service','flag','src_bytes','dst_bytes','hot','count','srv_count','diff_srv_rate','dst_host_count','dst_host_srv_count','dst_host_same_srv_rate','dst_host_diff_srv_rate','dst_host_same_src_port_rate','dst_host_serror_rate'])
Y.head(10)

   class
0      1
1      1
2      0
3      1
4      1
5      0
6      0
7      0
8      0
9      0

In [17]:
X_Train, X_Test, Y_Train, Y_Test = train_test_split(X, Y, test_size = 0.3 )

In [18]:
from sklearn import tree

clf = tree.DecisionTreeClassifier(criterion='entropy', random_state=0)
clf.fit(X_Train, Y_Train)

DecisionTreeClassifier(criterion='entropy', random_state=0)

Test ML Model

In [19]:
Test = clf.predict(X_Test)

In [20]:
Test

array([0, 0, 0, ..., 0, 0, 1])

In [21]:
Y_Test

       class
22309      0
19288      0
11516      0
10914      0
4322       1
...      ...
15057      0
4597       1
5894       0
7675       0
1817       1

[7558 rows x 1 columns]

MODEL EVALUATION

In [22]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [23]:
accuracy = accuracy_score(Y_Test,Test)
print("Model Accuracy = ",accuracy)

print("\n")

report = classification_report(Y_Test,Test)
print("Classification Report : \n",report)

Model Accuracy =  0.997221487165917


Classification Report :
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      3455
           1       1.00      1.00      1.00      4103

    accuracy                           1.00      7558
   macro avg       1.00      1.00      1.00      7558
weighted avg       1.00      1.00      1.00      7558

In [24]:
matrix = confusion_matrix(Y_Test,Test)
matrix

array([[3448,    7],
       [  14, 4089]])

In [25]:
from joblib import dump

In [26]:
dump(clf,'./../savedModels/model.joblib')

['./../savedModels/model.joblib']